package spms.server.model;
// Generated Apr 11, 2016 12:21:00 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ActiveGames generated by hbm2java
 */
public class ActiveGames  implements java.io.Serializable {


     private Integer activeGameId;
     private GameType gameType;
     private Date createdTime;
     private String generatorFile;
     private Set connectionses = new HashSet(0);

    public ActiveGames() {
    }

	
    public ActiveGames(GameType gameType, Date createdTime, String generatorFile) {
        this.gameType = gameType;
        this.createdTime = createdTime;
        this.generatorFile = generatorFile;
    }
    public ActiveGames(GameType gameType, Date createdTime, String generatorFile, Set connectionses) {
       this.gameType = gameType;
       this.createdTime = createdTime;
       this.generatorFile = generatorFile;
       this.connectionses = connectionses;
    }
   
    public Integer getActiveGameId() {
        return this.activeGameId;
    }
    
    public void setActiveGameId(Integer activeGameId) {
        this.activeGameId = activeGameId;
    }
    public GameType getGameType() {
        return this.gameType;
    }
    
    public void setGameType(GameType gameType) {
        this.gameType = gameType;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public String getGeneratorFile() {
        return this.generatorFile;
    }
    
    public void setGeneratorFile(String generatorFile) {
        this.generatorFile = generatorFile;
    }
    public Set getConnectionses() {
        return this.connectionses;
    }
    
    public void setConnectionses(Set connectionses) {
        this.connectionses = connectionses;
    }




}


