package spms.server.model;
// Generated Feb 28, 2016 11:10:24 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Connections generated by hbm2java
 */
public class Connections  implements java.io.Serializable {


     private int sessionId;
     private ActiveGames activeGames;
     private String clientIp;
     private Date connectTime;
     private String status;

    public Connections() {
    }

	
    public Connections(int sessionId, ActiveGames activeGames, String clientIp, Date connectTime) {
        this.sessionId = sessionId;
        this.activeGames = activeGames;
        this.clientIp = clientIp;
        this.connectTime = connectTime;
    }
    public Connections(int sessionId, ActiveGames activeGames, String clientIp, Date connectTime, String status) {
       this.sessionId = sessionId;
       this.activeGames = activeGames;
       this.clientIp = clientIp;
       this.connectTime = connectTime;
       this.status = status;
    }
   
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    public ActiveGames getActiveGames() {
        return this.activeGames;
    }
    
    public void setActiveGames(ActiveGames activeGames) {
        this.activeGames = activeGames;
    }
    public String getClientIp() {
        return this.clientIp;
    }
    
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }
    public Date getConnectTime() {
        return this.connectTime;
    }
    
    public void setConnectTime(Date connectTime) {
        this.connectTime = connectTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


