package spms.server.model;
// Generated Feb 28, 2016 11:10:24 AM by Hibernate Tools 3.6.0



/**
 * FinishGames generated by hbm2java
 */
public class FinishGames  implements java.io.Serializable {


     private FinishGamesId id;
     private int score;

    public FinishGames() {
    }

    public FinishGames(FinishGamesId id, int score) {
       this.id = id;
       this.score = score;
    }
   
    public FinishGamesId getId() {
        return this.id;
    }
    
    public void setId(FinishGamesId id) {
        this.id = id;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }




}


