package spms.server.model;
// Generated Apr 11, 2016 12:21:00 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GameType generated by hbm2java
 */
public class GameType  implements java.io.Serializable {


     private Integer gameId;
     private String gameName;
     private String gameDesc;
     private String domainFile;
     private String generatorCmd;
     private int gameLavel;
     private Set finishGameses = new HashSet(0);
     private Set activeGameses = new HashSet(0);

    public GameType() {
    }

	
    public GameType(String gameName, String domainFile, String generatorCmd, int gameLavel) {
        this.gameName = gameName;
        this.domainFile = domainFile;
        this.generatorCmd = generatorCmd;
        this.gameLavel = gameLavel;
    }
    public GameType(String gameName, String gameDesc, String domainFile, String generatorCmd, int gameLavel, Set finishGameses, Set activeGameses) {
       this.gameName = gameName;
       this.gameDesc = gameDesc;
       this.domainFile = domainFile;
       this.generatorCmd = generatorCmd;
       this.gameLavel = gameLavel;
       this.finishGameses = finishGameses;
       this.activeGameses = activeGameses;
    }
   
    public Integer getGameId() {
        return this.gameId;
    }
    
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }
    public String getGameName() {
        return this.gameName;
    }
    
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }
    public String getGameDesc() {
        return this.gameDesc;
    }
    
    public void setGameDesc(String gameDesc) {
        this.gameDesc = gameDesc;
    }
    public String getDomainFile() {
        return this.domainFile;
    }
    
    public void setDomainFile(String domainFile) {
        this.domainFile = domainFile;
    }
    public String getGeneratorCmd() {
        return this.generatorCmd;
    }
    
    public void setGeneratorCmd(String generatorCmd) {
        this.generatorCmd = generatorCmd;
    }
    public int getGameLavel() {
        return this.gameLavel;
    }
    
    public void setGameLavel(int gameLavel) {
        this.gameLavel = gameLavel;
    }
    public Set getFinishGameses() {
        return this.finishGameses;
    }
    
    public void setFinishGameses(Set finishGameses) {
        this.finishGameses = finishGameses;
    }
    public Set getActiveGameses() {
        return this.activeGameses;
    }
    
    public void setActiveGameses(Set activeGameses) {
        this.activeGameses = activeGameses;
    }




}


