package spms.client;
// Generated Feb 20, 2016 2:20:47 PM by Hibernate Tools 3.6.0



/**
 * FinishGames generated by hbm2java
 */
public class FinishGames  implements java.io.Serializable {


     private FinishGamesId id;
     private GameType gameType;
     private int score;

    public FinishGames() {
    }

    public FinishGames(FinishGamesId id, GameType gameType, int score) {
       this.id = id;
       this.gameType = gameType;
       this.score = score;
    }
   
    public FinishGamesId getId() {
        return this.id;
    }
    
    public void setId(FinishGamesId id) {
        this.id = id;
    }
    public GameType getGameType() {
        return this.gameType;
    }
    
    public void setGameType(GameType gameType) {
        this.gameType = gameType;
    }
    public int getScore() {
        return this.score;
    }
    
    public void setScore(int score) {
        this.score = score;
    }




}


