/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spms.client.ui;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import spms.client.ActiveGame;
import spms.client.CreateGame;
import spms.client.GameType;
import spms.client.TCPClient;

/**
 *
 * @author yazeedalmusharraf
 */
public class ClientFrame extends javax.swing.JFrame {

    public static ClientFrame frame;
    public static JTabbedPane tabPanel;
    public static TCPClient tcp;

    public void viewConnectPanel() {
        JPanel connPanel = new ConnectPanel();
        tabPanel.removeAll();
        tabPanel.addTab("Connect To Server", connPanel);
  

    }

    public void viewHomePanel() {

        JPanel homePanel = new HomePanel();

        tabPanel.removeAll();
        tabPanel.addTab("Home", homePanel);
                 JPanel result = new ResultPanel();
        tabPanel.addTab("Result", result);

        //pack();
        this.setVisible(true);

    }

    public void viewStartPanel(GameType game) {

        JPanel startPanel = new StartGamePanel(game);

        tabPanel.removeAll();
        tabPanel.addTab("Start Game", startPanel);
                 JPanel result = new ResultPanel();
        tabPanel.addTab("Result", result);

        //pack();
        this.setVisible(true);
        

    }

    public void viewWaitingPanel(CreateGame creator) {

        JPanel waitingPanel = new WaitingPanel(creator);
        ((WaitingPanel) waitingPanel).setDomainFile(creator.getDomainfile());
        tabPanel.removeAll();
        tabPanel.addTab("Waiting", waitingPanel);
                 JPanel result = new ResultPanel();
        tabPanel.addTab("Result", result);

        //pack();
        this.setVisible(true);

    }

    public void viewWaitingPanel(ActiveGame active) {

        JPanel waitingPanel = new WaitingPanel(active);
        ((WaitingPanel) waitingPanel).setDomainFile(active.getDomainfile());
        tabPanel.removeAll();
        tabPanel.addTab("Waiting", waitingPanel);
                 JPanel result = new ResultPanel();
        tabPanel.addTab("Result", result);

        //pack();
        this.setVisible(true);

    }

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {

        initComponents();
        
        tabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addContainerGap())
        );
        viewConnectPanel();
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (tcp != null) {
            tcp.close();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        frame = new ClientFrame();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
